# Generated by Django 4.2.7 on 2023-11-12 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('developer', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ranks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('local', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('details', models.CharField(max_length=200)),
                ('total', models.FloatField()),
                ('status', models.CharField(max_length=200)),
                ('stream_games', models.BooleanField(default=False)),
                ('priority_order', models.BooleanField(default=False)),
                ('desired_mastery', models.IntegerField()),
                ('current_mastery', models.IntegerField()),
                ('number_of_wins', models.IntegerField()),
                ('number_of_games', models.IntegerField()),
                ('ranked_genre', models.IntegerField()),
                ('lp_Gain', models.IntegerField()),
                ('current_lp', models.FloatField(max_length=99)),
                ('request_recipient', models.DateTimeField(auto_now_add=True)),
                ('request_creation_date', models.DateTimeField(auto_now_add=True)),
                ('the_require_price', models.FloatField()),
                ('current_rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_rank', to='ui.ranks')),
                ('desired_rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desired_rank', to='ui.ranks')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.servers')),
            ],
        ),
    ]
