# Generated by Django 4.2.7 on 2023-11-13 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_rename_ranks_rank'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameTypes',
            new_name='GameType',
        ),
        migrations.RenameModel(
            old_name='Requests',
            new_name='Request',
        ),
        migrations.RenameModel(
            old_name='Servers',
            new_name='Server',
        ),
    ]
