# Generated by Django 4.2.7 on 2023-11-13 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0003_rename_gametypes_gametype_rename_requests_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='current_rank',
        ),
    ]
