# Generated by Django 4.2.7 on 2023-11-13 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0004_remove_request_current_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='desired_rank',
        ),
        migrations.DeleteModel(
            name='Rank',
        ),
    ]
