# Generated by Django 4.2.7 on 2023-11-17 05:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0014_alter_request_request_creation_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameType',
        ),
        migrations.RemoveField(
            model_name='request',
            name='current_rank',
        ),
        migrations.RemoveField(
            model_name='request',
            name='desired_rank',
        ),
        migrations.RemoveField(
            model_name='request',
            name='server',
        ),
        migrations.AlterField(
            model_name='request',
            name='request_creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 17, 12, 53, 2, 796725)),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_recipient',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 17, 12, 53, 2, 796725)),
        ),
        migrations.DeleteModel(
            name='Rank',
        ),
        migrations.DeleteModel(
            name='Server',
        ),
    ]
