# Generated by Django 4.2.7 on 2023-11-17 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0015_delete_gametype_remove_request_current_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 17, 13, 38, 31, 464132)),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_recipient',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 17, 13, 38, 31, 464132)),
        ),
    ]
