# Generated by Django 4.2.7 on 2023-11-17 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0016_alter_request_request_creation_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
