# Generated by Django 4.2.7 on 2023-11-17 13:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library_db', '0003_gametype_server'),
        ('uprank', '0002_delete_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('details', models.CharField(max_length=200)),
                ('total', models.FloatField()),
                ('status', models.CharField(max_length=200)),
                ('stream_games', models.BooleanField(default=False)),
                ('priority_order', models.BooleanField(default=False)),
                ('desired_mastery', models.IntegerField()),
                ('current_mastery', models.IntegerField()),
                ('number_of_wins', models.IntegerField()),
                ('number_of_games', models.IntegerField()),
                ('ranked_genre', models.IntegerField()),
                ('lp_Gain', models.IntegerField()),
                ('current_lp', models.FloatField(max_length=99)),
                ('request_recipient', models.DateTimeField()),
                ('request_creation_date', models.DateTimeField()),
                ('the_require_price', models.FloatField()),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_db.server')),
            ],
        ),
    ]
