# Generated by Django 4.2.7 on 2023-11-17 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_db', '0003_gametype_server'),
        ('uprank', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='current_rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_rank', to='library_db.rank'),
        ),
        migrations.AlterField(
            model_name='request',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='library_db.server'),
        ),
    ]
