# Generated by Django 4.2.7 on 2023-11-18 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uprank', '0006_request_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='current_lp',
            field=models.FloatField(max_length=99, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='current_mastery',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='desired_mastery',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='details',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='number_of_games',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='number_of_wins',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='ranked_genre',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_creation_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_recipient',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='the_require_price',
            field=models.FloatField(null=True),
        ),
    ]
