# Generated by Django 4.2.7 on 2023-11-18 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uprank', '0007_alter_request_current_lp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='lp_Gain',
            field=models.IntegerField(choices=[(1, '14 LP or less'), (2, '15 LP or more'), (3, '20 LP or more'), (4, '25 LP or more'), (5, '34 LP or more')], null=True),
        ),
    ]
